### ISSUE TITLE
Use a `c_bool` instead of `bool` directly to ensure we're not bitten by `2` being used for example

### ISSUE THREAD

**Issue by poliorcetics** [HarfangLab/endpoint-sec#27]
I'm just realizing this now, but isn't this unsafe? Aren't bools in C allowed to have values other than 0/1? We may want to replace this with some c_bool type.

This can be turned into an issue and delegated for later.

_Originally posted by @roblabla in https://github.com/HarfangLab/endpoint-sec/pull/14#discussion_r1418766788_

**Comment by roblabla** [comment]
It turns out I was wrong. C bools aren't allowed to have values other than false and true (which are _generally_ represented as 0 and 1, at least on all platforms we care about). There is no c_bool type.
